### ISSUE TITLE
Utdanning: Undervisningsgruppe med flere fag som ikke er felles for elevene

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-informasjonsmodell#101]
Enkelte undervisningsgrupper underviser i flere fag, men alle elevene har ikke samme fag.

Eksempelvis gjøres dette for fremmedspråk hvor noen av elevene har tatt språket på ungdomsskolen.

**Comment by asgeirn** [comment]
@asgeirn: Sjekk med BAS og VIS hvordan dette ser ut i praksis.

**Comment by asgeirn** [comment]
Dette planlegger vi å løse med Fagmedlemskap, ref. #149

**Comment by torleifg** [comment]
Løses med #149

**Comment by torleifg** [comment]
https://fintlabs.atlassian.net/browse/INFM-32
