### ISSUE TITLE
Documentation link is not correct

### ISSUE THREAD

**Issue by OlaStalberg** [FINTLabs/fint-informasjonsmodell#128]
![image](https://user-images.githubusercontent.com/36536861/68011872-b9889a80-fc88-11e9-84c2-4fbc570984b9.png)
The link to wiki-page is not correct.

**Comment by asgeirn** [comment]
@torleifg Denne også?

https://informasjonsmodell.felleskomponent.no/docs/kompleksedatatyper_periode/~slutt?v=release-3.5.0

**Comment by asgeirn** [comment]
@torleifg Ugh, la merke til en annen feil: 

> #### Eksempel
> 01.01.1999T00:00:00Z

Det skulle vært _1999-01-01T00:00:00Z_
