### ISSUE TITLE
Utdanning: Beskrive kompetansen til lærer (skoleressurs)

### ISSUE THREAD

**Issue by torleifg** [FINTLabs/fint-informasjonsmodell#131]
Behov/ønske om å kunne beskrive kompetansen til lærer (og evt. andre). Eksempelvis finne lærere/vikarer med relevant kompetanse for undervisning i et gitt fag.

**Comment by fsjovatsen** [comment]
Hei,

 

Vi hadde i dag et internt møte hos oss der vi diskuterte lagring og utveksling av kompetanse via FINT. Der kom det opp noen spørsmål. Hvordan er lagring av data om kompetanse tenkt løst i VIS? Det er sagt at HR-system skal være master for kompetansedata, og dermed bør kompetansedata i FINT hentes via adapter for lokale HR-system.

 

Spørsmål:

I og med at kompetanse mangler i datamodellen i FINT. Når er det planlagt at dette skal inn og når skal det ut på høring?
Tenker man å dele opp ulike typer kompetanse slik at data om undervisningskompetanse vil eies av VIS og hentes ut via egne objekter i VIS-adapteret?
Tenker man å lagre annen type kompetanse i VIS? I så fall, skal de hentes via FINT der disse dataene ligger i lokale HR-system?
 

Har dere noen svar på disse spørsmålene?

**Comment by fsjovatsen** [comment]
Høre med Møre og Romsdal hva som er det konkrete behovet.

**Comment by GoSoft-dev** [comment]
Lagt i Jira: INFM-253
Lukkes her
