### ISSUE TITLE
Utdanning: Programområdemedlemskap: Elevstatus

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-informasjonsmodell#139]
![image (3)](https://user-images.githubusercontent.com/58614/75808491-7863dc80-5d87-11ea-8df7-4c82004c3e79.png)

**Comment by asgeirn** [comment]
Variabel	Kode	Beskrivelse	Gyldig f.o.m.	Gyldig t.o.m.	Distr Plan	Distr Faktisk
Elevstatus
Detaljer	Elevstatus	S	Avbrutt hele programområdet	 	 	05.05.2014	 
Detaljer	Elevstatus	D	Deltidselev	 	 	05.05.2014	 
Detaljer	Elevstatus	E	Elev	 	 	05.05.2014	 
Detaljer	Elevstatus	M	Fagopplæring i skole	 	 	05.05.2014	 
Detaljer	Elevstatus	K	Lærekandidat i programområdet	 	 	05.05.2014	 
Detaljer	Elevstatus	L	Lærling i programområdet	 	 	05.05.2014	 
Detaljer	Elevstatus	I	Norsk utvekslingselev i utlandet	 	 	05.05.2014	 
Detaljer	Elevstatus	O	Oppdragsundervisning	 	 	05.05.2014	 
Detaljer	Elevstatus	P	Privatist	 	 	05.05.2014	 
Detaljer	Elevstatus	A	Spesialundervisning	 	 	05.05.2014	 
Detaljer	Elevstatus	U	Utenlands utvekslingselev i Norge	 	 	05.05.2014	 
Detaljer	Elevstatus	V	Voksen	 	 	05.05.2014

**Comment by asgeirn** [comment]
Er dette forskjellig fra Elevkategori?

**Comment by asgeirn** [comment]
Variabel	Kode	Beskrivelse	Gyldig f.o.m.	Gyldig t.o.m.	Distr Plan	Distr Faktisk
						
Detaljer	Fagstatus	S	Avbrutt opplæring i faget	 	 	05.05.2014	 
Detaljer	Fagstatus	E	Elev	 	 	05.05.2014	 
Detaljer	Fagstatus	M	Fagopplæring i skole	 	 	05.05.2014	 
Detaljer	Fagstatus	F	Fritatt	 	 	05.05.2014	 
Detaljer	Fagstatus	N	Nettundervisning	 	 	05.05.2014	 
Detaljer	Fagstatus	O	Oppdragsundervisning	 	 	05.05.2014	 
Detaljer	Fagstatus	P	Privatist	 	 	05.05.2014	 
Detaljer	Fagstatus	R	Realkompetansevurdert	 	 	05.05.2014	 
Detaljer	Fagstatus	A	Spesialundervisning	 	 	05.05.2014	 
Detaljer	Fagstatus	U	Utenlands utvekslingselev i Norge	 	 	05.05.2014	 
Detaljer	Fagstatus	V	Voksen	 	 	05.05.2014	 
Detaljer	Fagstatus	G	Godkjent fag fra tidligere	 	 	06.09.2018

**Comment by asgeirn** [comment]
Ja, Elevkategori og Elevstatus må skilles.  Ta med Vigo fageksperter for mer presis definisjon av begrepene.

**Comment by asgeirn** [comment]
- [ ] Opprett `Elevstatus` som kodeverk med relasjon fra Elevforhold
- [ ] Spiss definisjonene på Elevstatus og Elevkategori i dokumentasjonen

**Comment by torleifg** [comment]
Definisjoner av Elevstatus og Fagstatus i Udirs registreringshåndbok. http://regbok.udir.no/liste/?Tema=693

**Comment by GoSoft-dev** [comment]
Lagt i Jira: INFM-252
Lukkes her.
