### ISSUE TITLE
Mangler i forhold til rapportering/statistikk

### ISSUE THREAD

**Issue by fsjovatsen** [FINTLabs/fint-informasjonsmodell#144]
Foreløpige mangler:
- [ ] Varsler - antall - Om egen sakstype kan vi få ut dette ifm arkiv API-et til FINT (egne objekter i utdanningsmodellen)
- [ ] Fagsamtaler - antall - Om egen sakstype kan vi få ut dette ifm arkiv API-et til FINT (egne objekter i utdanningsmodellen)
- [ ] Elevsamtaler - antall - Om egen sakstype kan vi få ut dette ifm arkiv API-et til FINT (egne objekter i utdanningsmodellen)
- [ ] Egendefinerte felt i VIS (Er dette en tag om legges på objekter i VIS, styres det på skoleeier eller skole nivå)
- [ ] Tilrettelegginger på eksamen - Om egen sakstype kan vi få ut dette ifm arkiv API-et til FINT (egne objekter i utdanningsmodellen) Er det behov for å uttrykke type tiltak?
- [ ] Vikarløse timer - Fremkommer dette i timeplanen? Timeplansdelen i FINT må re-modelleres for å vise denne typen informasjon
- [ ] Vikar med lærere med undervisningskompetanse - Må berike datamodellen med undervisningskompetanse per lærer, er dette knyttet til fagkoden?
- [ ] Leverte årstimer til opplæring - Hvordan fremkommer dette i VIS?
- [ ] Planlagte og gjennomførte timer
- [ ] Avvik på mellom planlagte og gjennomførte - Samme som over?
- [ ] Data fra eksamenstrekk - Kan dette utledes fra eksamensgruppene + fagkode + eksamensform
- [ ] Fordelt på fag, 
- [ ] Skriftlig og muntlig 
- [ ] Over flere skoleår
- [ ] Gruppestørrelser 
- [ ] NUS opplysninger 
- [ ] Antall anmerkninger (Orden og Adferd)   - Om egen sakstype kan vi få ut dette ifm arkiv API-et til FINT (egne objekter i utdanningsmodellen)
- [ ] Elevfravær - timefraværet med hvilken time på dagen (1. til siste time) - Må berike datamodellen med fraværsdata, samt at VIS må eksponere denne informasjonen
- [ ] Elever med 
- [ ] Vurdering uten kommentar fordelt på fag

**Comment by asgeirn** [comment]
Denne må deles opp i flere biter som utredes nærmere.

**Comment by GoSoft-dev** [comment]
Lagt inn i Jira: INFM-251
Lukkes her
