### ISSUE TITLE
Personer uten fødselsnummer/D-nummer

### ISSUE THREAD

**Issue by fsjovatsen** [FINTLabs/fint-informasjonsmodell#145]
Jeg fikk en sak med en utenlandsk student som er tilknyttet en videregående skole gjennom  Erasmus+-programmet (https://www.erasmuspluss.no/ ). Vedkommende er lærerassistent ved en av våre videregående skoler våren 2020. Erasmus-studenter er her på stipend og mottar ikke noen ytelser fra fylket. Det skal da det ikke leveres skattekort og det utstedes derfor ikke D-nummer.

I HR-systemet vårt er studenten registrert med passnummer som id-nummer.
 
Utfordringen er at vedkommende ikke eksporteres til FINT siden fødselsnummer/d-nummer mangler, og dermed heller ikke kommer over i VIS. Har FINT vurdert å bruke passnummer som en alternativ identifikator på personressurser i administrasjonsdomenet for slike tilfeller?

**Comment by fsjovatsen** [comment]
Kan dette løses ved å bruke F-nummer:
http://regbok.udir.no/35004/3344/35042-1027331.html

Se https://informasjonsmodell.felleskomponent.no/docs/felles_person/~fodselsnummer?v=v3.4.0

**Comment by berntjoh** [comment]
F-nummer gjelder i utgangspunktet for personer med elevtilknytning til skole.  

En Erasmus-student er i denne sammenhengen ikke elev, men mer å sammenlikne med norske lærerstudenter som har praksis på en videregående skole. Disse blir registrert i HR-systemet (uten skattekort). Det er fra HR at VIS henter persondata om disse.

I Visma HRM er det tre hovedvarianter av identifikasjonsnummer for en person, fødselsnummer, D-nummer og internasjonalt identitetsnummer.

Å eventuelt i stedet for D-nummer legge inn et fiktivt fødselsnummer generert slik det er beskrevet i u-dirs registeringshåndbok, vil etter min mening bryte med «semantikken» til D-nummer-feltet. Det kan også være at det kan bli kollisjoner mellom fiktive fødselsnummer og D-nummer.

**Comment by GoSoft-dev** [comment]
Lagt i Jira: INFM-250
Lukkes her
