### ISSUE TITLE
Utdanning: Fagmedlemskap: Fagstatus

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-informasjonsmodell#149]
- [x] Opprett `Fagmedlemskap` som et `Gruppemedlemskap` mellom `Elevforhold` og `Fag`.
- [x] Legg til kodeverk `Fagstatus` fra `Fagmedlemskap`, basert på [B07 Fagstatus (udir)](http://regbok.udir.no/felt/?B07_Fagstatus&Id=1014315)

**Comment by asgeirn** [comment]
@torleifg Kunne du legge til dokumentasjon på Medlemsstatus basert på http://regbok.udir.no/felt/?B07_Fagstatus&Id=1014315 ?

**Comment by fsjovatsen** [comment]
Må utredes om det er behov.
