### ISSUE TITLE
Felles: Person: Skoleressurs

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-informasjonsmodell#152]
Relasjon mellom Person og Skoleressurs

**Comment by asgeirn** [comment]
Ref FINTmodels/fint-model-resource#6

**Comment by torleifg** [comment]
Enveis relasjon, skoleressurs til person, fordi det er vanskelig å få til en toveis relasjon per i dag.

**Comment by torleifg** [comment]
Relasjon til en person i administrasjonsdomenet.
