### ISSUE TITLE
Utdanning: Vurdering

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-informasjonsmodell#159]
Offisielle karakterer, jf. https://lovdata.no/forskrift/2006-06-23-724/§4-32

1. Halvårsvurdering
2. Standpunktkarakter
3. Eksamenskarakter

Sluttvurderinger, jf. https://lovdata.no/forskrift/2006-06-23-724/§4-11

1. Standpunktkarakter
2. Eksamenskarakter
3. Karakterar til fag-/sveineprøve og kompetanseprøve

Mangler i Vurdering:

- Bytt ut Vurdering med spesifikke og konkrete typer
- Dato
- Relasjoner til termin og skoleår
- Underveisvurdering

Halvårsvurdering er beskrevet i forskrift til opplæringsloven: https://lovdata.no/forskrift/2006-06-23-724/§4-9

B13.Karaktertermin:  http://regbok.udir.no/35004/3344/35042-1018635.html

**Comment by asgeirn** [comment]
https://www.regjeringen.no/no/dokumenter/nou-2019-23/id2682434/

**Comment by torleifg** [comment]
https://fintlabs.atlassian.net/browse/INFM-30
