### ISSUE TITLE
Administrasjon: Arbeidsforhold: Yrkeskode

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-informasjonsmodell#162]
7-sifret yrkeskode basert på STYRK98.  Rapporteres gjennom a-ordningen.

https://www.ssb.no/arbeid-og-lonn/yrkeskatalogen

Bør også være et felles kodeverk.

**Comment by GoSoft-dev** [comment]
Lagt i Jira: INFM-248
Lukkes her
