### ISSUE TITLE
Arkiv: Part / sakspart er komplekse datatyper

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-informasjonsmodell#164]
Ikke alle arkiv har et enhetlig partsregister.  I stedet er informasjon om part og sakspart registrert direkte på saksmappe.

De har ikke alltid registrert identifikatorer som fødselsnummer / organisasjonsnummer.

**Comment by torleifg** [comment]
`Korrespondanse` byttet ut med `Korrespondansepart` i `Registrering`. `Korrespondansepart` omgjort til kompleks datatype med relasjon til `KorrespondansepartType`.

**Comment by torleifg** [comment]
Gjøre det samme med `Part`

**Comment by torleifg** [comment]
`Partsinformasjon` byttet ut med `Part` i `Registrering`, `Mappe`, og `Dokument`. `Part`omgjort til kompleks datatype med relasjon til `PartRolle`.
