### ISSUE TITLE
Utdanning: Undervisningsgruppe: Termin

### ISSUE THREAD

**Issue by oleanders** [FINTLabs/fint-informasjonsmodell#17]

**Comment by asgeirn** [comment]
- [ ] Er det andre grupper som knyttes til termin?
- [ ] Opprett Termin som kodeverk med relasjon til skoleår.
- [ ] Opprett Skoleår som kodeverk (?)

Ref. OneRoster "Academic session"

**Comment by asgeirn** [comment]
Relasjonen bør være `0..*` for å uttrykke at en gruppe går over flere terminer.

**Comment by torleifg** [comment]
I et utvalg datasett kan det se ut til at termin også gjelder for basisgrupper, enkelte grupper har angitt V19 osv. i tittel. Et alternativ kan være å legge skoleår og termin på den abstrakte gruppe.

**Comment by torleifg** [comment]
Finnes det kun én instans av for eksempel termin V19 dersom det legges til i kodeverk? Tror det vil være flere varianter av terminer innenfor én og samme skoleeier, det vil si at de har ulikt start- og sluttidspunkt (det kan være behov for å fange opp denne informasjonen).
