### ISSUE TITLE
Vurdering: IKO-modellen

### ISSUE THREAD

**Issue by OlaStalberg** [FINTLabs/fint-informasjonsmodell#171]
Hva er forskjellen mellom Underveisvurdering og Midtveisvurdering fra IKO-modellen. Skal vi ta høyde for det og hvordan kan modellen støtte det.

**Comment by torleifg** [comment]
Midtveisvurdering, etter IKO-modellen, må utredes nærmere før det tas inn i modellem,

**Comment by GoSoft-dev** [comment]
Lagt i Jira: INFM-247
Lukkes her
