### ISSUE TITLE
Vurdering: (Karakter)termin

### ISSUE THREAD

**Issue by OlaStalberg** [FINTLabs/fint-informasjonsmodell#172]
Fra Kjell, Trøndelag:
"Termin" kan gå lengre eller kortere enn en vanlig "karaktertermin". Det kan løpe over skoleårsgrenser.
Er det støtte for det i modellen?
Eksempel: En student som får ikke får lærlingskontrakt, men får det senere. Tidsperioden kan da løpe fra november til november, dermed utover et vanlig skoleår. Også kortere perioder som november til februar er mulig.

**Comment by torleifg** [comment]
Skoleår og termin er kodeverk som kommer fra kilden. Kan omfatte mer en standard skoleår og termin.

**Comment by GoSoft-dev** [comment]
Lagt i Jira: INFM-246
Lukkes her
