### ISSUE TITLE
Vurdering: Flere karakterer i ett fag

### ISSUE THREAD

**Issue by OlaStalberg** [FINTLabs/fint-informasjonsmodell#173]
Er det mulig å ha en kommentar til en karakterverdi? 

Det kan være flere enn 1 karakter i en "termin" og knyttet til samme "fagkode". Eksamen trenger å ha en kode for karakterverdi og en karakter for tilstedeværelse. 
https://www.udir.no/eksamen-og-prover/dokumentasjon/vitnemal-og-kompetansebevis/foring-vitnemal-kompetansebevis-vgs/3-merknader-til-vitnemal-og-kompetansebevis/#3.1-fagmerknader 

Burde modellen skille mellom karakterer som skal på vitnemålet og de som ikke skal det?
Eksempel: En forbedringskarakter, der det er to karakterer. Modellen må kunne håndtere IDer for dette.

**Comment by torleifg** [comment]
Se karakterstatus.

**Comment by torleifg** [comment]
Det er mulig å legge til en kommentar på selve vurderingen.

**Comment by GoSoft-dev** [comment]
Saken er lagt inn i Jira: INFM-245
Lukkes her.
