### ISSUE TITLE
Vurdering: Karakteransvarlig

### ISSUE THREAD

**Issue by OlaStalberg** [FINTLabs/fint-informasjonsmodell#174]
Modellen må kunne vise hvem som setter karakteren. Det kan være flere enn 1 person som er ansvarlig for karakteren. Men det er kun en som er føringsansvarlig.

**Comment by torleifg** [comment]
Sjekke begreper. Karakteransvarlig og føringsansvarlig.

**Comment by torleifg** [comment]
Karakteransvarlig er et etablert begrep i VIS og ellers i skolesammenheng. Finner ikke tilsvarende referanser til føringsansvarlig.

**Comment by GoSoft-dev** [comment]
Denne er lagt i Jira: INFM-244
Lukkes her
