### ISSUE TITLE
Vurdering: Kompetansemål knyttet til underveisvurdering

### ISSUE THREAD

**Issue by OlaStalberg** [FINTLabs/fint-informasjonsmodell#175]
Vi må vite hvilke kompetansemål som er knyttet til en vurdering. Årsaken er at noen vurderinger ikke er knyttet til alle kompetansemålene.

**Comment by torleifg** [comment]
Gjelder underveisvurdering og i all hovedsak vurderingssituasjoner som er knyttet til et utvalg av kompetansemål. Vurderingssituasjoner skal utredes nærmere før det tas inn i modellen.

**Comment by GoSoft-dev** [comment]
Lagt in i Jira: INFM-243
Denne lukkes her.
