### ISSUE TITLE
Vurdering: Vurderingstyper og underveisvurdering

### ISSUE THREAD

**Issue by OlaStalberg** [FINTLabs/fint-informasjonsmodell#177]
Støtter modellen alle typer vurdering? "Vurderingstype" mangler blant annet "underveisvurdering"? 

Det er viktig å få med alle de ulike typene med underveisvurdering som lager grunnlaget for de formelle underveisvurderingene.

**Comment by torleifg** [comment]
Modellen vil i første omgang støtte formelle underveis- og sluttvurderinger. Vurderingstype er et kodeverk fra fagsystemet og vil inneholde det det er og vil bli behov for av typer vurderinger.

**Comment by GoSoft-dev** [comment]
Det er i dag Underveis-, Halvårs- og Slutt- vurderinger både som fagvurderinger og Ordensvurderingen.

Lukker denne saken.
