### ISSUE TITLE
Vurdering: Relasjoner til karakterer

### ISSUE THREAD

**Issue by OlaStalberg** [FINTLabs/fint-informasjonsmodell#179]
Burde modellen skille mellom karakterer som skal på vitnemålet og de som ikke skal det? 
Eksempel: En forbedringskarakter, der det er to karakterer. Modellen må kunne håndtere IDer for dette.

**Comment by torleifg** [comment]
Alternativ - vi uttrykker til enhver tid gjeldende karakter.

**Comment by torleifg** [comment]
Overlapper med #173
