### ISSUE TITLE
Kulturminne: Fredet hus i privat eie (FRIP): Navn på eiendom

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-informasjonsmodell#180]
Fra flere hold har det kommet ønske om eiendommens navn som et metadatafelt.

Begreper som brukes:
- Objekt
- Kulturminnenavn
- Navn på objekt / eiendom

I tillegg nevnes Adresse som et felt, men det kan kanskje inngå i eiendommens navn?

**Comment by asgeirn** [comment]
Begrepet `tittel` arves allerede fra Noark, så det kan vi ikke benytte.  Kommune og fylke får vi fra `Matrikkelinformasjon`, så etter mitt syn er ikke den nødvendig.

Kan vi bruke begrepet `navn`?

**Comment by torleifg** [comment]
Nettopp. Evt. eiendomsnavn?

**Comment by torleifg** [comment]
bygningsNavn. jmf. #183
