### ISSUE TITLE
Vurdering: Fagskolen

### ISSUE THREAD

**Issue by torleifg** [FINTLabs/fint-informasjonsmodell#186]
Fagskolen må rapportere til DBH (https://dbh.nsd.uib.no/) med egne krav. Maritime fag på fagskolen må rapportere etter egne krav til Sjøfartsdirektoratet (Nye krav gjelder fra 1.1.2021). Det er ulike linjer på Fagskolene som har forskjellige rapporteringskrav som må dekkes.

**Comment by GoSoft-dev** [comment]
Lagt i Jira: INFM-242
Lukkes her
