### ISSUE TITLE
Utdanning: Skoleårsplanlegging

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-informasjonsmodell#189]
Har det noen gang vært vurdert om noe av informasjonen fra skoleårsplanleggingen i skoleadministrativt system skal tilgjengeliggjøres i FINTs informasjonsmodell? 

I en ideell verden hadde systemet gjort stillingsplan (ressursplanleggingen) for skolene tilgjengelig for skoleeier, men det er ikke gjort. 

Det betyr at skoleeier ikke kan få til en sammenstilling av alle skolenes ressursplaner, men må gå inn på en og en skole for å se deres ressursplan. 

Hadde dette vært tilgjengelig i informasjonsmodellen kunne en jo koblet til analyseverktøy og enkelt kunne sammenstilt alle skolenes ressursplaner og fått en totaloversikt i fylkeskommunen.

**Comment by GoSoft-dev** [comment]
Der er en del saker i Jira som går på dette etter gjennomgang av VIS.
Lukker denne.
