### ISSUE TITLE
Arkiv: Mappe: klasse skal være 0..*

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-informasjonsmodell#197]
Relasjonen `klasse` må være `0..*`.

**Comment by torleifg** [comment]
Haster? 3.6.1?

**Comment by asgeirn** [comment]
Ja, det bør egentlig inn snarest, ja.    Jeg holder på å implementere modellen nå, vi kan planlegge en release neste uke for å fange opp eventuelt andre feil.

Men versjonsnummeret blir 3.6.10 i tråd med konvensjonen for nummerering, numrene mellom hele tiere er forbeholdt tekniske oppdateringer av den genererte koden.
