### ISSUE TITLE
Mulighet for synlighet og skjerming av informasjon

### ISSUE THREAD

**Issue by oleanders** [FINTLabs/fint-informasjonsmodell#20]
Hva med tilgangsstyring i modellen opp mot elever som har adressesperre (kode 6 eller 7)?
I noen tilfeller (antar at dette gjelder kode 6) skal også navn skjermes. Hvordan kan dette håndteres både i uttrekk/transport og i VFS?

Informasjon om koding er ikke i modellen i dag. FINT må avklare hvor ansvaret for maskering / filtering av informasjon ligger. Løsning for dette kommer i en senere release.

**Comment by asgeirn** [comment]
https://www.infotorg.no/nyheter/personer-med-sperret-adresse : 
> Den tilpassede tjenesten leverer offentlig godkjente postadresser i bosteds-/ hovedadressefeltet, slik at banken kan benytte opplysningene direkte i sine systemer uten å foreta systemtekniske endringer.

http://www.vigoiks.no/systeminformasjon/informasjon-vigo-opplaering/generell-informasjon/post-til-elever-med-sperret-hemmelig-adresse : 
> Post til elever med sperret/hemmelig adresse kan sendes til Kripos og så vil de sende dette videre til elevens korrekte adresse.
> 
> Post sendes til Kripos på følgende adresse/syntaks:
>
>_Mottakers navn_
>SOT6
>Pb. 8163, Dep
>0034 Oslo
