### ISSUE TITLE
Personvern: Spesifisere hvilken rolle en behandling er aktuell for

### ISSUE THREAD

**Issue by berntjoh** [FINTLabs/fint-informasjonsmodell#206]
Avhengig av hvilken rolle (elev/ansatt) eller roller en person har i organisasjonen, vil det være forskjellige behandlinger som er aktuelle for personen å gi samtykke til. Profilbilde for elever i VIS,  profilbilde for ansatte i Office 365 er to eksempler. Der personen gir og trekker samtykker er det ønskelig at kun behandlinger relatert til personens rolle(r) blir presentert for personen. Dette bør være uttrykt i informasjonsmodellen

**Comment by GoSoft-dev** [comment]
Saken er overført til Jira. INFM-239
