### ISSUE TITLE
Administrasjon: Relasjon timerPerUke på Arbeidsforhold burde hete uketimetall

### ISSUE THREAD

**Issue by oleanders** [FINTLabs/fint-informasjonsmodell#39]
Når navnet på klassen Uketimetall ble endret, burde også relasjonen på arbeidsforholdet blitt endret til samme navn.

**Comment by oleanders** [comment]
#39 er ikke fikset i v2.0.10. Arbeidsforhold: 
![image](https://user-images.githubusercontent.com/26850/31326861-3fd51a60-accb-11e7-91a3-fd1b563f978d.png)

**Comment by asgeirn** [comment]
Stemmer, jeg nevnte feil issue i commit-meldingen :-/ det var #36, #37 og #38 jeg mente.

**Comment by asgeirn** [comment]
Dersom vi skifter navn på denne attributten blir det strengt tatt en "breaking change", slik at vi må opp til `v3.0.0`.

**Comment by oleanders** [comment]
Ja, det er ikke noe som MÅ gjøres nå. Men noe vi bør rettes ved en v3.0.0.

**Comment by oleanders** [comment]
Vi kan også sette relasjonen `timerPerUke` som `deprecated`, og legge til relasjonen `uketimetall`.
