### ISSUE TITLE
Endre dato og tidsangivelse

### ISSUE THREAD

**Issue by fsjovatsen** [FINTLabs/fint-informasjonsmodell#59]
Alternativene er:

1. Alt angis som lokal tid
2. Dele Dato og tid i to felter

**Comment by asgeirn** [comment]
I realiteten bruker vi ikke tidspunkt noe sted i modellen.  Vi burde heller hatt felter med kun dato.

For å kunne gjøre dette uten å ødelegge data må alle kilder bruke tidspunkt 00:00:00 UTC, og ikke konvertere fra midnatt lokal tid.
