### ISSUE TITLE
Utdanning: Dato på medlemskap

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-informasjonsmodell#83]
Det er ingen gyldighetsperiode knyttet direkte til medlemskapsobjektet. Periode er knyttet til gruppen medlemskapsobjektet er relatert til. For eksempel vil en undervisningsgruppe vanligvis ha en gyldighetsperiode som svarer til et skoleår. Et medlemskap i denne gruppen gjelder dermed for hele skoleåret.

Dersom det var knyttet periode direkte til medlemskapsobjektet, ville det vært mulig å uttrykke at elever både ble med og sluttet i gruppen i løpet av skoleåret og når det skjedde. Det kan også være at en undervisningsgruppe bytter lærer.

**Comment by berntjoh** [comment]
Når det gjelder medlemskap i gruppene årstrinn, programområde, utdanningsprogram og fag er perioden ikke et skoleår, men gyldighetsperioden for tilhørende grepkode. Elever vil dermed være tilknyttet grepkoder for fag, trinn osv de ikke nødvendigvis tar/går på nåværende skoleår. Igjen vil periode på medlemskap løse dette problemet.

**Comment by asgeirn** [comment]
1. Introduser en kompleks datatype `Gruppemedlemskap` med relasjoner til alle gruppe-typer, samt status, med `periode` som felt.
2. Legg til et `0..*` felt `gruppemedlemskap` i Utdanningsforhold
3. Legg til `0..1` relasjon `(medlems)status` til kodeverk som kan representere fagstatus (#149)
4. Opprett klasse `Medlemsstatus` i Kodeverk

**Comment by asgeirn** [comment]
Eksempel:

```
{
    "medlemskap": [
        {
            "periode": {
                "start": "2020-12-03",
                "slutt": "2021-01-13"
            },
            "_links": {
                "status": [
                    {
                        "href": "https://api.felleskomponent.no/utdanning/kodeverk/medlemsstatus/XXX"
                    }
                ],
                "undervisningsgruppe": [
                    {
                        "href": "https://api.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/5226088"
                    },
                    {
                        "href": "https://api.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/5226089"
                    }

                ]
            }
        },
        {
            "periode": {
                "start": "2020-12-03",
                "slutt": "2021-01-13"
            },
            "_links": {
                "fagstatus": [
                    {
                        "href": "https://api.felleskomponent.no/utdanning/kodeverk/fagstatus/XXX"
                    }
                ],
                "basisgruppe": [
                    {
                        "href": "https://api.felleskomponent.no/utdanning/timeplan/basisgruppe/systemid/5226088"
                    }
                ]
            }
        }
    ],
    "_links": {
        "skole": [
            {
                "href": "https://api.felleskomponent.no/utdanning/utdanningsprogram/skole/systemid/30036"
            }
        ],
        "undervisningsgruppe": [
            {
                "href": "https://api.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/5226088"
            },
            {
                "href": "https://api.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/5226087"
            },
            {
                "href": "https://api.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/5226086"
            },
            {
                "href": "https://api.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/5226085"
            }
        ],
        "programomrade": [
            {
                "href": "https://api.felleskomponent.no/utdanning/utdanningsprogram/programomrade/systemid/MDMDD1--1-"
            }
        ],
        "basisgruppe": [
            {
                "href": "https://api.felleskomponent.no/utdanning/elev/basisgruppe/systemid/895800"
            }
        ],
        "kontaktlarergruppe": [
            {
                "href": "https://api.felleskomponent.no/utdanning/elev/kontaktlarergruppe/systemid/895800_507773"
            }
        ]
    }
}
```

**Comment by berntjoh** [comment]
@asgeirn Er tanken med gruppemedlemskap at det skal være et objekt per gruppe utdanningsforholdet er tilknyttet, eller et objekt som inneholder alle gruppene et utdanningforhold er tilknyttet?  Dersom et gruppemedlemskapobjekt skal inneholde alle gruppene, må det ikke da generes et nytt medlemskap hver gang det er en endring i hvilke grupper utdanningsforholdet er tilknyttet.

**Comment by asgeirn** [comment]
> @asgeirn Er tanken med gruppemedlemskap at det skal være et objekt per gruppe utdanningsforholdet er tilknyttet, eller et objekt som inneholder alle gruppene et utdanningforhold er tilknyttet? Dersom et gruppemedlemskapobjekt skal inneholde alle gruppene, må det ikke da generes et nytt medlemskap hver gang det er en endring i hvilke grupper utdanningsforholdet er tilknyttet.

@berntjoh Slik vi modellerer det nå blir det ett gruppemedlemskap per gruppe hvert elevforhold er medlem av.

![Gruppemedlemskap (1)](https://user-images.githubusercontent.com/58614/80359661-6e89c180-887e-11ea-97c6-b95eea0eabe3.png)

**Comment by asgeirn** [comment]
Vi fjerner `status` - disse blir introdusert senere, ref #139 og #149
